### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by negsadr** [UBC-MDS/MacroView#43]
Group 9
> **Congratulations on finishing milestone 1!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  
> We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
> If anything is unclear, please feel free to ask questions in this issue thread.

---

## Submission instructions
rubric={mechanics:4}

Well done!

## Section 1: Motivation and Purpose
rubric={reasoning:8,writing:2}

- [ ] `proposal.md`: There isn't a minimal description of the app. What will the app do? What is it's main purpose? **-2 reasoning** 

## Section 2: Description of the data
rubric={reasoning:8,writing:2}

- [ ] `proposal.md` - **Dataset description section**: There is not evidence data quality analysis. Are there missing values? Are these values an important percentage of the dataset?. **-1 reasoning**

## Section 3: Research questions and usage scenarios
rubric={reasoning:12,writing:2}

- [ ] `proposal.md` - **Persona**: IPersona**: In the persona description it is not specified their needs as user and/or the potential benefits that the app could for this person **-2 reasoning**

- [ ] `proposal.md` - **Persona**: The level of detail provided in the persona description is not sufficient and the number of words in it is less than 200-300 words. **-2 reasoning**

Comments:
-What is lacking is information on what the app provides and how it will help Bob (benefits).

## Section 4:  Description of your app & sketch
rubric={viz:10, writing:2, reasoning: 3}

Well done!

## Section 5:  Team work contract and collaborative documentation
rubric={reasoning:4}

Well done!

## Code of Conduct
rubric={reasoning:1}

Well done!

## Contribution guidelines
rubric={reasoning:1}

Well done!

**Comment by samson-bakos** [comment]
Hi Negar, addressing your feedback, mostly regarding the proposal document:

* There isn't a minimal description of the app. What will the app do? What is its main purpose?:

`a nutrition tracking dashboard that enables health-conscious individuals to accurately track and visualize their macronutrient intake.` -- we state here our apps main functionality. It allows health conscious users to track and visualize their food and nutrient intake. Users enter their food intake, and it visualizes it against goals they set. We state its purpose of `empowering individuals to make informed and healthy lifestyle choices`

* There is not evidence data quality analysis. Are their missing values? Are these values an important percentage of the dataset?

We didn't speak about missing values because there aren't any. There are no relevant missing values in the dataset; while not every single possible food is represented, all foods present have a complete set of information for the relevant quantities we are visualizing.

* In the persona description it is not specified their needs as user and/or the potential benefits that the app could for this person: 
`Bob is a UBC student who wants to keep track of his nutrition` - needs. Anyone who has tried this with pen and paper quickly loses their mind, which is why apps for this purpose exist.

`Frustrated with existing platforms (which have recently moved to much more aggressive premium business models -- i.e. MyFitnessPal, Lifesum), Bob is in search of a nutrition tracking platform that is free, publicly accessible and uses reliable datasets` -- benefits, open source non premium model

`Bob needs to be able to quickly [look up ingredients] from a reliable database, and have the platform pull up the most relevant values`, `Bob will [weigh out the food] he is making for himself, and enter the amounts as he goes. He wants to see his current totals of macronutrients for the day and his remaining amounts in both written and visualization formats` -- uses/functionality. It provides a platform for nutrition tracking both in terms of data lookup and visualization. He enters his daily food intake and it is visualized against his current targets. 

While the persona portion of the dataset is short, we feel it captures the necessary information. Nutrition calculators are an exceedingly well known class of applications and we did not feel the need to litigate people's motivations for using them. Our main motivation in this project was to create an open source version of an existing, well known service and as such in general we focus mainly on the specific differences between our service and existing well known apps.

**Comment by J99thoms** [comment]
Hi @negsadr. I agree with @samson-bakos's comments above. Could you please take another look at [our proposal](https://github.com/UBC-MDS/MacroView/blob/v0.1.0/reports/proposal.md)? There most certainly **is** a minimal description of the app which describes what will the app do as well as its main purpose. And the persona definitely **does** specify the needs of the user and the potential benefits of the app for the user.

You state that "what is lacking is information on what the app provides and how it will help Bob (benefits)." Could you please explain how the following excerpt from our proposal doesn't provide that exact information: 

> Bob needs to be able to quickly [look up ingredients] from a reliable database, and have the platform pull up the most relevant values. Bob generally makes healthy choices, so he’s not too concerned with micronutrients -- he is mostly concerned with macronutrients to synergize with his exercise and manage his weight.
>
> When using the app, Bob will [weigh out the food] he is making for himself, and enter the amounts as he goes. He wants to see his current totals of macronutrients for the day and his remaining amounts in both written and visualization formats (e.g. a barplot with a target bar). 

In particular, the part "He wants to see his current totals of macronutrients for the day and his remaining amounts in both written and visualization formats (e.g. a barplot with a target bar)." provides a pretty clear description of exactly what the app will do for Bob. 

I do concede that our audience persona is less than 200-300 words, as it comes in at 168 words. However, I still feel that the persona provides a sufficient level of detail to motivate the purpose of our app. It seems like we're being docked for writing concisely. Sure, we could add a bunch of extra words like "very" and go more into detail about Bob's personal background, but I feel that doing so would simply make the persona's word count longer without actually making the app's purpose more clear.

**Comment by ChesterAiGo** [comment]
Following up the persona part in specific:
Persona: The level of detail provided in the persona description is not sufficient and the number of words in it is less than 200-300 words. -2 reasoning

I just double-checked and did not see anything thing about the word count requirement explicitly listed in section "Section 3: Research questions and usage scenarios" in the criteria. 

Reference: https://pages.github.ubc.ca/MDS-2022-23/DSCI_532_viz-2_students/materials/assignments/milestone1.html#section-3-research-questions-and-usage-scenarios

**Comment by negsadr** [comment]
Sorry, I'm getting back to you late!

Congratulations on finishing your project and the course!

Regarding your comments on the grading of Milestone 1:

I've removed the penalties for the following **(+4)**: 
- [ ] `proposal.md`: There isn't a minimal description of the app. What will the app do? What is it's main purpose? **-2 reasoning** 
- [ ] `proposal.md` - **Persona**: IPersona**: In the persona description it is not specified their needs as user and/or the potential benefits that the app could for this person **-2 reasoning**

However, for the word count and data quality analysis, I'm afraid there's nothing I can do as the instructions in the rubric are very clear. Have you talked to Florencia about it?
